/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbayasRouteImport } from './routes/abayas'
import { Route as AccessoriesRouteImport } from './routes/accessories'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as DressesRouteImport } from './routes/dresses'
import { Route as HijabSuppliesRouteImport } from './routes/hijab-supplies'
import { Route as IsdalatRouteImport } from './routes/isdalat'
import { Route as KhimarRouteImport } from './routes/khimar'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ShoesRouteImport } from './routes/shoes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbayasRoute = AbayasRouteImport.update({
  id: '/abayas',
  path: '/abayas',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesRoute = AccessoriesRouteImport.update({
  id: '/accessories',
  path: '/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const DressesRoute = DressesRouteImport.update({
  id: '/dresses',
  path: '/dresses',
  getParentRoute: () => rootRouteImport,
} as any)
const HijabSuppliesRoute = HijabSuppliesRouteImport.update({
  id: '/hijab-supplies',
  path: '/hijab-supplies',
  getParentRoute: () => rootRouteImport,
} as any)
const IsdalatRoute = IsdalatRouteImport.update({
  id: '/isdalat',
  path: '/isdalat',
  getParentRoute: () => rootRouteImport,
} as any)
const KhimarRoute = KhimarRouteImport.update({
  id: '/khimar',
  path: '/khimar',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoesRoute = ShoesRouteImport.update({
  id: '/shoes',
  path: '/shoes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abayas': typeof AbayasRoute
  '/accessories': typeof AccessoriesRoute
  '/articles': typeof ArticlesRoute
  '/dresses': typeof DressesRoute
  '/hijab-supplies': typeof HijabSuppliesRoute
  '/isdalat': typeof IsdalatRoute
  '/khimar': typeof KhimarRoute
  '/sales': typeof SalesRoute
  '/shoes': typeof ShoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abayas': typeof AbayasRoute
  '/accessories': typeof AccessoriesRoute
  '/articles': typeof ArticlesRoute
  '/dresses': typeof DressesRoute
  '/hijab-supplies': typeof HijabSuppliesRoute
  '/isdalat': typeof IsdalatRoute
  '/khimar': typeof KhimarRoute
  '/sales': typeof SalesRoute
  '/shoes': typeof ShoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abayas': typeof AbayasRoute
  '/accessories': typeof AccessoriesRoute
  '/articles': typeof ArticlesRoute
  '/dresses': typeof DressesRoute
  '/hijab-supplies': typeof HijabSuppliesRoute
  '/isdalat': typeof IsdalatRoute
  '/khimar': typeof KhimarRoute
  '/sales': typeof SalesRoute
  '/shoes': typeof ShoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abayas'
    | '/accessories'
    | '/articles'
    | '/dresses'
    | '/hijab-supplies'
    | '/isdalat'
    | '/khimar'
    | '/sales'
    | '/shoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abayas'
    | '/accessories'
    | '/articles'
    | '/dresses'
    | '/hijab-supplies'
    | '/isdalat'
    | '/khimar'
    | '/sales'
    | '/shoes'
  id:
    | '__root__'
    | '/'
    | '/abayas'
    | '/accessories'
    | '/articles'
    | '/dresses'
    | '/hijab-supplies'
    | '/isdalat'
    | '/khimar'
    | '/sales'
    | '/shoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbayasRoute: typeof AbayasRoute
  AccessoriesRoute: typeof AccessoriesRoute
  ArticlesRoute: typeof ArticlesRoute
  DressesRoute: typeof DressesRoute
  HijabSuppliesRoute: typeof HijabSuppliesRoute
  IsdalatRoute: typeof IsdalatRoute
  KhimarRoute: typeof KhimarRoute
  SalesRoute: typeof SalesRoute
  ShoesRoute: typeof ShoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abayas': {
      id: '/abayas'
      path: '/abayas'
      fullPath: '/abayas'
      preLoaderRoute: typeof AbayasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories': {
      id: '/accessories'
      path: '/accessories'
      fullPath: '/accessories'
      preLoaderRoute: typeof AccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dresses': {
      id: '/dresses'
      path: '/dresses'
      fullPath: '/dresses'
      preLoaderRoute: typeof DressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hijab-supplies': {
      id: '/hijab-supplies'
      path: '/hijab-supplies'
      fullPath: '/hijab-supplies'
      preLoaderRoute: typeof HijabSuppliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/isdalat': {
      id: '/isdalat'
      path: '/isdalat'
      fullPath: '/isdalat'
      preLoaderRoute: typeof IsdalatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khimar': {
      id: '/khimar'
      path: '/khimar'
      fullPath: '/khimar'
      preLoaderRoute: typeof KhimarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shoes': {
      id: '/shoes'
      path: '/shoes'
      fullPath: '/shoes'
      preLoaderRoute: typeof ShoesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbayasRoute: AbayasRoute,
  AccessoriesRoute: AccessoriesRoute,
  ArticlesRoute: ArticlesRoute,
  DressesRoute: DressesRoute,
  HijabSuppliesRoute: HijabSuppliesRoute,
  IsdalatRoute: IsdalatRoute,
  KhimarRoute: KhimarRoute,
  SalesRoute: SalesRoute,
  ShoesRoute: ShoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
